//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_HabibullinDmitry.TournamentBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achivements
    {
        public int If_Achivements { get; set; }
        public Nullable<int> Id_Match { get; set; }
        public string Achive { get; set; }
        public Nullable<int> Id_PStats { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual PlayerStats PlayerStats { get; set; }
    }
}
