//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_HabibullinDmitry.TournamentBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionLimits
    {
        public int Id_RegLimits { get; set; }
        public Nullable<int> Id_TLimits { get; set; }
        public Nullable<int> Id_Region { get; set; }
    
        public virtual Regions Regions { get; set; }
        public virtual TournamentLimits TournamentLimits { get; set; }
    }
}
