//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_HabibullinDmitry.TournamentBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPlayer
    {
        public int Id_TP { get; set; }
        public Nullable<int> Id_Team { get; set; }
        public Nullable<int> Id_Player { get; set; }
    
        public virtual MatchPlayer MatchPlayer { get; set; }
        public virtual Team Team { get; set; }
    }
}
