//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_HabibullinDmitry.TournamentBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentPlace
    {
        public int Id_TPlace { get; set; }
        public Nullable<int> Id_Tournament { get; set; }
        public Nullable<int> Id_Team { get; set; }
        public Nullable<int> Id_GCP { get; set; }
        public Nullable<int> Id_Status { get; set; }
    
        public virtual GClassPreference GClassPreference { get; set; }
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
